# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tutorial',
                'doc_host': 'https://apetulante.github.io',
                'git_url': 'https://github.com/apetulante/nbdev_tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.core': { 'nbdev_tutorial.core.add': ('simple_functions.html#add', 'nbdev_tutorial/core.py'),
                                     'nbdev_tutorial.core.multiply': ('simple_functions.html#multiply', 'nbdev_tutorial/core.py')}}}
