# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/simple_functions.ipynb.

# %% auto 0
__all__ = ['add', 'multiply']

# %% ../nbs/simple_functions.ipynb 4
def add(x,y):
    "Multiply two numbers"
    return x+y

def multiply(x,y):
    return x*y
